on:
  push:
    branches: 
      - 8devices

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get install -y git subversion build-essential flex wget gawk unzip man file python2.7 zlib1g-dev libssl-dev libncurses5-dev ocaml-nox
      - name: build
        run: |
          git clone --depth 1 https://github.com/felix-fly/qsdk-8devices.git qsdk
          cd qsdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f

          wget https://raw.githubusercontent.com/felix-fly/router-map/main/8devices.config -O .config

          # Keep version same to the current firmware
          wget https://raw.githubusercontent.com/felix-fly/router-map/main/ipq6000.vermagic -O vermagic
          sed -i 's/$(SH_FUNC).*vermagic$/cp $(TOPDIR)\/vermagic $(LINUX_DIR)\/\.vermagic/g' include/kernel-defaults.mk
          sed -i 's/$(firstword.*md5sum))/$(shell cat $(LINUX_DIR)\/\.vermagic)/g' package/kernel/linux/Makefile

          make defconfig
          make -j$(nproc) || make -j1 V=s
          cd ..
          mkdir bin
          mkdir bin/packages
          mv qsdk/bin/ipq/*.bin bin
          mv qsdk/bin/ipq/*.tar.bz2 bin
          find qsdk/bin/ipq -name \*.ipk -exec cp {} bin/packages \;
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: bin
